### ISSUE TITLE
0.4.7.5 特质報錯

### ISSUE THREAD

**Issue by Paul-16098** [MissedHeart/Degrees-of-Lewdity-DolSims#2]
0.4.7.5 Error (:: Bedroom): <<traits>>: cannot execute widget: 0.4.7.5 Error (:: Bedroom): <\<set>>: bad evaluation: Cannot read properties of undefined (reading 'canvasfilter')
<\<traits>>
console log:
[liodaneobpalkcmcgmomdecikleajokl-1717752269499.log](https://github.com/user-attachments/files/15732352/liodaneobpalkcmcgmomdecikleajokl-1717752269499.log)
save:
[degrees-of-lewdity-20240607-172344.save.txt](https://github.com/user-attachments/files/15732506/degrees-of-lewdity-20240607-172344.save.txt)
mod list:
```txt
ModI18N
Simple Frameworks
GameOriginalImagePack
paul_mod
cheat extended
Free Attitudes
NoAutoReBuyTrash
NPC Avatars Mod (SF)
LongerCombat
Love Locket-Text Expansion
BESC
BEEESSS_WAX
地下开局
Dol_MoreOption
self_tailor
blush_idle
Terraria Expand Mod v0.1.1
DOL_Magic
Whitney_Extra_Mod
ReOverfits
DOL_tattoo_v1.0
Eliminate Spaces
Victorian_Full_WIP
Bailey rent mod
StrangeGarden
DoLSims
BJ_Extend
```
mod loader log:
[ModLoaderLog.txt](https://github.com/user-attachments/files/15733981/ModLoaderLog.txt)

Degrees of Lewdity 0.4.7.5
chs-alpha2.0.2
mod loader v2.16.2

win10 x64
nwjs sdk v0.88.0

**Comment by MissedHeart** [comment]
疑似与某个mod冲突，具体未确定
